# Using transformers

In [11]:
from transformers import AutoTokenizer,AutoModel
import torch

In [3]:
#just information don't runn both either setup one
#device = "mps" if torch.backends.mps.is_available() else "cpu"   # for apple GPU
# device = torch.device("cuda:0" if torch.cuda.is_available() else "cpu") # for NVIDIA
torch.device("mps" if torch.backends.mps.is_available() else "cpu")

device(type='mps')

In [12]:
#download and load the model
tokenizer = AutoTokenizer.from_pretrained("emilyalsentzer/Bio_ClinicalBert")
model = AutoModel.from_pretrained("emilyalsentzer/Bio_ClinicalBert")

sentences = ["This framework generates embeddings for each input sentence"]

#Tokenize the sentences
encoded_input = tokenizer(sentences, padding=True, truncation=True, max_length=128, return_tensors='pt')

#compute token embeddings
with torch.no_grad():
    model_output = model(**encoded_input)
    

Some weights of the model checkpoint at emilyalsentzer/Bio_ClinicalBert were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight', 'cls.predictions.decoder.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


In [6]:
print(encoded_input)

{'input_ids': tensor([[  101,  1142,  8297, 21241,  9712,  4774,  3408,  1116,  1111,  1296,
          7758,  5650,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [7]:
print(encoded_input['input_ids'].shape)

torch.Size([1, 13])


In [8]:
for token in encoded_input['input_ids'][0]:
    print(tokenizer.decode(token))

[CLS]
this
framework
generates
em
##bed
##ding
##s
for
each
input
sentence
[SEP]


In [13]:
ids = encoded_input['input_ids']
print(ids)

tensor([[  101,  1142,  8297, 21241,  9712,  4774,  3408,  1116,  1111,  1296,
          7758,  5650,   102]])


In [10]:
mask = encoded_input['attention_mask']
print(mask)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])


In [13]:
output = model(ids, mask)
final_layer = output.last_hidden_state

print(final_layer)

tensor([[[ 0.2158, -0.1084,  0.1876,  ...,  0.2099,  0.0843,  0.0233],
         [-0.3009, -0.1544,  0.3384,  ...,  0.1853,  0.4096,  0.2572],
         [ 0.2038,  0.1068,  0.1621,  ..., -0.0106,  0.0322, -0.0404],
         ...,
         [-0.0062,  0.0316,  0.0100,  ...,  0.1434, -0.1350,  0.2606],
         [ 0.3250, -0.0937,  0.0700,  ...,  0.0812, -0.2481,  0.1599],
         [ 0.0678,  0.5106, -0.7916,  ..., -0.0949,  0.5474,  0.7905]]],
       grad_fn=<NativeLayerNormBackward0>)


# Using BERT model

In [1]:
from transformers import BertTokenizer, BertModel
import torch

In [4]:
sentences = ["This framework generates embeddings for each input sentence"]

In [6]:
tokenizer1 = BertTokenizer.from_pretrained("bert-base-uncased")
encoded_input1 = tokenizer1(sentences, padding=True, truncation=True, return_tensors="pt")
model = BertModel.from_pretrained('bert-base-uncased')


with torch.no_grad():
    model_output1 = model(**encoded_input1)

print(encoded_input1)

Some weights of the model checkpoint at bert-base-uncased were not used when initializing BertModel: ['cls.predictions.transform.LayerNorm.bias', 'cls.seq_relationship.weight', 'cls.predictions.transform.LayerNorm.weight', 'cls.seq_relationship.bias', 'cls.predictions.transform.dense.bias', 'cls.predictions.bias', 'cls.predictions.transform.dense.weight']
- This IS expected if you are initializing BertModel from the checkpoint of a model trained on another task or with another architecture (e.g. initializing a BertForSequenceClassification model from a BertForPreTraining model).
- This IS NOT expected if you are initializing BertModel from the checkpoint of a model that you expect to be exactly identical (initializing a BertForSequenceClassification model from a BertForSequenceClassification model).


{'input_ids': tensor([[  101,  2023,  7705, 19421,  7861,  8270,  4667,  2015,  2005,  2169,
          7953,  6251,   102]]), 'token_type_ids': tensor([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]]), 'attention_mask': tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])}


In [8]:
ids1 = encoded_input1['input_ids']
print(ids1)

tensor([[  101,  2023,  7705, 19421,  7861,  8270,  4667,  2015,  2005,  2169,
          7953,  6251,   102]])


In [7]:
for token in encoded_input1['input_ids'][0]:
    print(tokenizer1.decode(token))

[ C L S ]
t h i s
f r a m e w o r k
g e n e r a t e s
e m
# # b e d
# # d i n g
# # s
f o r
e a c h
i n p u t
s e n t e n c e
[ S E P ]


# Vectors Similarity Check

In [15]:
# Cosine-similarity check
from sklearn.metrics.pairwise import cosine_similarity

cosine_similarity_check = cosine_similarity(ids, ids1)

print(cosine_similarity_check)

[[0.98353806]]
